### ISSUE TITLE
Deployed docs not rendering anything correctly

### ISSUE THREAD

**Issue by 70Gage70** [LuxDL/DocumenterVitepress.jl#183]
Building locally with `DocumenterVitepress.dev_docs("build", md_output_path = "")` looks good

![Image](https://github.com/user-attachments/assets/3f6e6db2-0361-45f5-96fd-ed5e07a755ed)

But deploying to github gives this (also, none of the links work):

![Image](https://github.com/user-attachments/assets/4999755a-f5da-4bed-a373-d78ab1b965eb)

See the live site [here](https://70gage70.github.io/Sargassum.jl/). I'm honestly stumped on this, I've tried to copy the`make.jl`  and `documentation.yaml` as closely as possible but nothing seems to be working. 

<details>

<summary>My make.jl</summary>

```julia
using Documenter, DocumenterVitepress
using Sargassum
using CairoMakie

# try
#     itps_load(Sargassum.SargassumBOMB._ITPS_SCRATCH.x)
# catch
#     try 
#         itps_default_construct(download = true)
#     catch
#         nothing
#     end
# end

### VITEPRESS
makedocs(
    sitename = "Sargassum.jl",
    format = MarkdownVitepress(
        # md_output_path = ".", # LOCAL ONLY
        # build_vitepress = false, # LOCAL ONLY
        repo = "github.com/70Gage70/Sargassum.jl",
        devbranch = "master", 
        devurl = "dev";
    ),
    modules = [Sargassum],
    warnonly = true,
    checkdocs=:all,
    draft=false,
    source="src", 
    build="build",
    # clean = false, # LOCAL ONLY
)

### DOCUMENTER
# makedocs(
#     sitename = "Sargassum.jl",
#     format = Documenter.HTML(),
#     modules = [Sargassum, SargassumBOMB, SargassumColors, SargassumFromAFAI, SargassumInterface],
#     pages = [
#         "Home" => "index.md",
#         "Getting Started" => "getting-started.md",
#         "Packages" => [
#             "SargassumInterface.jl" => [
#                 "Tutorial" => "s-interface.md",
#                 "API" => "s-interface-api.md"],
#             "SargassumBOMB.jl" => [
#                 "Tutorial" => "s-bomb.md",
#                 "API" => "s-bomb-api.md",
#                 "Examples API" => "s-bomb-examples-api.md"],
#             "SargassumFromAFAI.jl" => [
#                 "Tutorial" => "s-afai.md",
#                 "API" => "s-afai-api.md"],
#             "SargassumColors.jl" => [
#                 "Tutorial" => "s-colors.md",
#                 "API" => "s-colors-api.md"],
#         ]
#     ],
#     warnonly = true
# )

deploydocs(;
    repo = "github.com/70Gage70/Sargassum.jl",
    target = "build", 
    versions = nothing,
    branch = "gh-pages",
    devbranch = "master",
    push_preview = true
)

```

</details>

<details>

<summary>My documentation.yaml</summary>

```yaml
name: Documentation

on:
  push:
    branches:
      - main
      - master
    tags: ['*']
  pull_request:

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
      - name: Pull Julia cache
        uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.Registry.add("General"); Pkg.Registry.add(Pkg.RegistrySpec(url = "https://github.com/70Gage70/SargassumRegistry")); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); using Sargassum; itps_default_construct(download = true)'
      - name: Build and deploy docs
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100" # for Plots.jl plots (if you have them)
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
```

</details>

The full repo is [here](https://github.com/70Gage70/Sargassum.jl).

It's strange because e.g. [here](https://github.com/70Gage70/Sargassum.jl/blob/gh-pages/assets/lxbzdxo.CheBV7Kp.png) we can see that the build is doing the right things (making the figures in `@example` blocks) but somehow the site itself is just broken.

EDIT: Copied wrong version of make.jl.
