### ISSUE TITLE
How to make hero logo switch between dark and light automatically?

### ISSUE THREAD

**Issue by Moelf** [LuxDL/DocumenterVitepress.jl#284]
Right now if one can have a fixed logo file if one includes this at the top of the `index.md`:
```
---
layout: home
hero:
  name: "BinnedDistributionFit.jl"
  tagline: "Maximum-likelihood fitting of binned distributions"
  image:
    src: logo.svg
    alt: BinnedDistributionFit_Logo
  actions:
    - theme: brand
      text: "Quick Start"
      link: /quickstart
    - theme: alt
      text: APIs
      link: /95-reference
---
```

If I have `logo_light.svg` and `logo_dark.svg`, is there a way to make it auto switch depends on user's theme?

**Comment by Moelf** [comment]
I was hoping for something from VitePress like:
```
 image:
    src: logo.svg
    alt: BinnedDistributionFit_Logo
 image_dark:
    src: logo_dark.svg
    alt: BinnedDistributionFit_Logo
```

if not I guess there's nothing to do here.
